# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bW5-DNXQXd-lTfgmZar5SndPd5RWoo5n
"""

import requests
import json
import os
import time
from datetime import datetime
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

headers = {
    "User-Agent": "TrendPulse/1.0"
}

categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}
collected_stories = []
category_count = {
    "technology": 0,
    "worldnews": 0,
    "sports": 0,
    "science": 0,
    "entertainment": 0
}

MAX_PER_CATEGORY = 25


def get_category(title):
    title_lower = title.lower()

    for category, keywords in categories.items():
        for keyword in keywords:
            if keyword in title_lower:
                return category

    return None

try:
    response = requests.get(TOP_STORIES_URL, headers=headers)
    response.raise_for_status()
    top_story_ids = response.json()[:500]

except requests.RequestException as e:
    print("Failed to fetch top stories:", e)
    top_story_ids = []

for category in categories.keys():

    for story_id in top_story_ids:
        if category_count[category] >= MAX_PER_CATEGORY:
            break

        try:
            story_response = requests.get(
                ITEM_URL.format(story_id),
                headers=headers
            )
            story_response.raise_for_status()

            story = story_response.json()

            if not story:
                continue

            title = story.get("title", "")

            assigned_category = get_category(title)
            if assigned_category == category:

                collected_stories.append({
                    "post_id": story.get("id"),
                    "title": title,
                    "category": assigned_category,
                    "score": story.get("score", 0),
                    "num_comments": story.get("descendants", 0),
                    "author": story.get("by", "unknown"),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                })

                category_count[category] += 1

        except requests.RequestException as e:
            print(f"Failed to fetch story {story_id}: {e}")
            continue
    time.sleep(2)

if not os.path.exists("data"):
    os.makedirs("data")

file_name = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(file_name, "w", encoding="utf-8") as file:
    json.dump(collected_stories, file, indent=4)

print(f"Collected {len(collected_stories)} stories. Saved to {file_name}")